[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors https://app.storyblok.com;"
    X-Frame-Options = "ALLOW-FROM https://app.storyblok.com"
    Access-Control-Allow-Origin = "app.storyblok.com"
    Access-Control-Allow-Credentials = "true"
